name: Build, Test, and Push to ACR

on:
  push:
    branches:
      - main

env:
  ACR_NAME: fleetmanagementsystem               # e.g. myregistry (no .azurecr.io)
  ACR_LOGIN_SERVER: fleetmanagementsystem.azurecr.io
  IMAGE_NAME: fleetmanagementsystem

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # REQUIRED for Managed Identity (OIDC)
      contents: read

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build solution
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Run unit tests ✅      
      - name: Test
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Results
          path: '**/test-results.trx'
          reporter: dotnet-trx


      # Azure login using Managed Identity (OIDC)
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - run: az acr check-health -n $ACR_NAME --yes

      # Login to ACR
      - name: Login to ACR
        run: az acr login --name $ACR_NAME

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build \
            -f FleetManagementSystem-.Net/Dockerfile \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} \
            FleetManagementSystem-.Net

      # Push Docker image to ACR
      - name: Push Docker Image
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}
          
      # Update App Service Config to Deploy Container
      - name: Update container config
        run: |
            az webapp config container set \
              --name FleetManagementSystem \
              --resource-group Fleet-Management-System \
              --container-image-name $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}
      
